# Generated by Django 4.2.7 on 2025-06-08 23:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "room_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("layer_level", models.IntegerField(default=1)),
                ("is_wired_only", models.BooleanField(default=False)),
                ("requires_fragmentation", models.BooleanField(default=False)),
                ("anonymous_mode_only", models.BooleanField(default=False)),
                ("auto_destroy_messages_hours", models.IntegerField(default=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Chat Room",
                "verbose_name_plural": "Chat Rooms",
                "db_table": "chat_rooms",
            },
        ),
        migrations.CreateModel(
            name="RoomHistory",
            fields=[
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("room_name", models.CharField(max_length=50)),
                ("event_type", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("layer_count_at_time", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "room_history",
            },
        ),
    ]
