# Generated by Django 4.2.7 on 2025-06-08 23:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmergencyBurn",
            fields=[
                (
                    "burn_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("burn_type", models.CharField(max_length=50)),
                ("burned_at", models.DateTimeField(auto_now_add=True)),
                ("objects_destroyed_count", models.IntegerField()),
                ("triggered_by_hash", models.CharField(max_length=64)),
                ("reason", models.CharField(default="emergency", max_length=200)),
            ],
            options={
                "db_table": "emergency_burns",
            },
        ),
        migrations.CreateModel(
            name="KeyRotation",
            fields=[
                (
                    "rotation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rotated_at", models.DateTimeField(auto_now_add=True)),
                ("key_type", models.CharField(max_length=50)),
                ("affected_objects_count", models.IntegerField()),
                (
                    "rotation_reason",
                    models.CharField(default="scheduled", max_length=100),
                ),
            ],
            options={
                "db_table": "key_rotations",
            },
        ),
        migrations.CreateModel(
            name="TrueAnonymousLayer",
            fields=[
                (
                    "layer_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("layer_name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                ("auto_destroy_at", models.DateTimeField(blank=True, null=True)),
                ("corruption_level", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Anonymous Layer",
                "verbose_name_plural": "Anonymous Layers",
                "db_table": "anonymous_layers",
            },
        ),
        migrations.CreateModel(
            name="LayerMapping",
            fields=[
                (
                    "mapping_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_hash", models.CharField(max_length=64)),
                ("layer_id", models.UUIDField()),
                ("encrypted_link", models.BinaryField()),
                ("salt", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "anonymous_mapping",
                "unique_together": {("user_hash", "layer_id")},
            },
        ),
        migrations.CreateModel(
            name="DataFragment",
            fields=[
                (
                    "fragment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fragment_index", models.IntegerField()),
                ("encrypted_data", models.BinaryField()),
                ("checksum", models.CharField(max_length=64)),
                ("belongs_to_type", models.CharField(max_length=50)),
                ("belongs_to_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "data_fragments",
                "unique_together": {("belongs_to_id", "fragment_index")},
            },
        ),
        migrations.CreateModel(
            name="AnonymousMessage",
            fields=[
                (
                    "message_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("layer_id", models.UUIDField()),
                ("room_name", models.CharField(max_length=100)),
                ("content_hash", models.CharField(max_length=64)),
                ("encrypted_content", models.BinaryField()),
                ("encryption_nonce", models.CharField(max_length=32)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_ephemeral", models.BooleanField(default=False)),
                ("auto_destroy_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "anonymous_messages",
                "indexes": [
                    models.Index(
                        fields=["layer_id", "timestamp"],
                        name="anonymous_m_layer_i_510665_idx",
                    ),
                    models.Index(
                        fields=["room_name", "timestamp"],
                        name="anonymous_m_room_na_dd7a69_idx",
                    ),
                ],
            },
        ),
    ]
