# Generated by Django 4.2.7 on 2025-06-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anonymization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousmessage",
            name="encryption_salt",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="anonymousmessage",
            index=models.Index(
                fields=["auto_destroy_at"], name="anonymous_m_auto_de_890285_idx"
            ),
        ),
    ]
